version: '3'
services:
  backend:
    image: thecodingmachine/php:7.2-v1-apache
    volumes:
        - ./backend:/var/www/html
    environment:
        PHP_EXTENSION_XDEBUG: 1
        PHP_INI_XDEBUG__REMOTE_HOST: 10.0.2.2
    ports:
        - "8088:80"
        - "9000:9000"
  front:
    image: node:10
    command: /bin/bash -c "npm install && npm run dev"
    working_dir: /src
    volumes:
        - ./front:/src
    environment:
        HOST: 0.0.0.0
        CHOKIDAR_USEPOLLING: 1
    ports:
        - "8080:8080"
    stdin_open: true
    tty: true
